# Step 5: Connect Frontend and Python Services

Write-Host "=== STEP 5: Connect Services ===" -ForegroundColor Cyan
Write-Host ""

Write-Host "INSTRUCTIONS:" -ForegroundColor Green
Write-Host ""
Write-Host "1. Get your Python Service URL from STEP 4"
Write-Host "   Example: https://kuber-nepali-service.vercel.app"
Write-Host ""
Write-Host "2. Go to Vercel Dashboard (https://vercel.com)"
Write-Host ""
Write-Host "3. Select 'Kuber_Timesheet' project"
Write-Host ""
Write-Host "4. Go to Settings → Environment Variables"
Write-Host ""
Write-Host "5. Find NEXT_PUBLIC_NEPALI_API_URL and update:"
Write-Host "   Old value: (empty or placeholder)"
Write-Host "   New value: https://kuber-nepali-service.vercel.app"
Write-Host ""
Write-Host "6. Click 'Save' or 'Update'"
Write-Host ""
Write-Host "7. Go to Deployments tab"
Write-Host ""
Write-Host "8. Click 'Redeploy' on the latest deployment"
Write-Host ""
Write-Host "9. Wait 2-3 minutes for redeployment"
Write-Host ""
Write-Host "✅ Your system is now fully connected!"
Write-Host ""
Write-Host "NEXT: Test your deployment"
Write-Host "- Go to: https://kuber-timesheet.vercel.app"
Write-Host "- You should see the login page"
Write-Host "- Try logging in (wait for admin to create test accounts)"
